#login
login:
    path: /
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Security:login }

login_route:
    path: /login
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Security:login_check }

#logout
logout:
    path: /logout

#registration
user_registration:
    path:     /register
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Registration:register }

#foto
_fotos:
    path: /fotos/
    defaults: { _controller: CaffeOlivuzzoAdminBundle:FotoClienti:index, page: 1 }
    requirements:
      id:  \d+

_foto_delete:
    path: /foto/delete/{id}
    defaults: { _controller: CaffeOlivuzzoAdminBundle:FotoClienti:delete }

_foto_update:
    path: /foto/update/{id}
    defaults: { _controller: CaffeOlivuzzoAdminBundle:FotoClienti:update }

#commenti
_comments:
    path: /comments/
    defaults: { _controller: CaffeOlivuzzoAdminBundle:CommentiClienti:index }
    requirements:
      id:  \d+

_comment_update:
    path: /comment/update/{id}
    defaults: { _controller: CaffeOlivuzzoAdminBundle:CommentiClienti:update }

_comment_delete:
    path: /comment/delete/{id}
    defaults: { _controller: CaffeOlivuzzoAdminBundle:CommentiClienti:delete }

#utenti
_utenti:
    path: /utenti
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Utenti:index }

_utente_delete:
    path: /utente/delete/{id}
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Utenti:delete }

_utente_update:
    path: /utente/update/
    defaults: { _controller: CaffeOlivuzzoAdminBundle:Utenti:update }
