# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        CaffeOlivuzzo\AdminBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        our_db_provider:
            entity:
                class: CaffeOlivuzzoAdminBundle:User
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                #redirect dopo login
                default_target_path: _comments
            logout:
                path:   /logout
                target: /login
            provider: our_db_provider
            remember_me:
                secret: 915dc97cab36a935cf59a8ac85f829475cba876e
                lifetime: 604800 # 1 week in seconds
                path:     /

        main:
            pattern:    ^/
            http_basic: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/comments, roles: ROLE_USER }
        - { path: ^/fotos, roles: ROLE_USER }
        - { path: ^/utenti, roles: ROLE_ADMIN }
